# Repository configuration for GitHub statistics collection
# Add new repositories here organized by technology category

repositories:
  AI/ML:
    # Core Deep Learning Frameworks (155k+ stars)
    - AUTOMATIC1111/stable-diffusion-webui  # 155k stars - Stable Diffusion WebUI
    - tensorflow/tensorflow                   # 191k stars - Google's ML framework
    - pytorch/pytorch                        # 92k stars - Facebook's ML framework
    - openai/whisper                         # 86k stars - Speech recognition
    - microsoft/ML-For-Beginners             # 75k stars - ML education
    - scikit-learn/scikit-learn              # 63k stars - Classical ML
    
    # Large Language Models & NLP (40k+ stars)
    - huggingface/transformers               # 148k stars - Transformer models
    - langchain-ai/langchain                 # 112k stars - LLM applications
    - meta-llama/llama                       # 58k stars - Meta's LLM
    - Significant-Gravitas/AutoGPT           # 177k stars - Autonomous GPT
    - ollama/ollama                          # 148k stars - Local LLM runner
    - vllm-project/vllm                      # 53k stars - LLM inference
    - huggingface/trl                        # 15k stars - RL for transformers
    - microsoft/DeepSpeed                    # 36k stars - Deep learning optimization
    - facebookresearch/llama                 # 44k stars - Original Llama
    
    # Generative AI & Computer Vision (20k+ stars)
    - comfyanonymous/ComfyUI                 # 84k stars - Node-based UI for AI
    - open-webui/open-webui                  # 104k stars - WebUI for LLMs
    - CompVis/stable-diffusion               # 70k stars - Original Stable Diffusion
    - LAION-AI/Open-Assistant               # 37k stars - Open chatbot
    - oobabooga/text-generation-webui       # 42k stars - Text generation UI
    - microsoft/DialoGPT                     # 12k stars - Conversational AI
    - openai/CLIP                           # 26k stars - Image-text understanding
    - facebookresearch/detectron2           # 30k stars - Object detection
    - ultralytics/yolov5                    # 51k stars - Object detection
    - roboflow/supervision                  # 25k stars - Computer vision toolkit
    
    # MLOps & Production (10k+ stars)
    - mlflow/mlflow                         # 19k stars - ML lifecycle management
    - wandb/wandb                           # 9k stars - Experiment tracking
    - iterative/dvc                         # 15k stars - Data version control
    - bentoml/BentoML                       # 7k stars - Model serving
    - feast-dev/feast                       # 6k stars - Feature store
    - kubeflow/kubeflow                     # 14k stars - ML on Kubernetes
    - ray-project/ray                       # 34k stars - Distributed computing
    - apache/airflow                        # 38k stars - Workflow orchestration
    
    # Data Science & Analytics (15k+ stars)
    - pandas-dev/pandas                     # 46k stars - Data manipulation
    - jupyter/notebook                      # 12k stars - Interactive computing
    - plotly/plotly.py                      # 16k stars - Interactive visualizations  
    - matplotlib/matplotlib                 # 20k stars - Python plotting
    - streamlit/streamlit                   # 36k stars - Data app framework
    - gradio-app/gradio                     # 33k stars - ML interfaces
    - facebook/prophet                      # 18k stars - Time series forecasting
    
    # Learning & Educational (10k+ stars)
    - microsoft/AI-For-Beginners            # 35k stars - AI education
    - fastai/fastbook                       # 23k stars - Deep learning book
    - ageron/handson-ml3                    # 28k stars - Hands-on ML book
    - karpathy/nn-zero-to-hero              # 12k stars - Neural networks course
    - microsoft/ai-agents-for-beginners     # 15k stars - AI agents course
    
    # Specialized AI Applications (8k+ stars)
    - openai/gym                            # 35k stars - RL environments  
    - Stability-AI/generative-models        # 25k stars - Generative models
    - xinntao/Real-ESRGAN                   # 28k stars - Image super-resolution
    - coqui-ai/TTS                          # 35k stars - Text-to-speech
    - suno-ai/bark                          # 36k stars - Audio generation
    - microsoft/semantic-kernel             # 22k stars - AI orchestration
    - langgenius/dify                       # 109k stars - LLM application platform
    - HumanSignal/label-studio              # 24k stars - Data labeling
    - cleanlab/cleanlab                     # 11k stars - Data-centric AI
    - voxel51/fiftyone                      # 10k stars - Computer vision datasets

  TypeScript:
    - nestjs/nest
    - prisma/prisma
    - adonisjs/core
    - typeorm/typeorm
    - sequelize/sequelize
    - trpc/trpc
    - fastify/fastify
    - taskforcesh/bullmq
    - mikro-orm/mikro-orm
    - drizzle-team/drizzle-orm
    - kysely-org/kysely
    - colinhacks/zod
    - winstonjs/winston
    - pinojs/pino
    - helmetjs/helmet
    - moleculerjs/moleculer
    - typestack/routing-controllers
    - lukeautry/tsoa
    - tsedio/tsed
    - lobehub/lobe-chat
    - vercel/ai

  "C# ASP.NET":
    - dotnet/aspnetcore
    - aspnetrun/run-aspnetcore-microservices
    - DapperLib/Dapper
    - jasontaylordev/CleanArchitecture
    - dotnet/efcore
    - App-vNext/Polly
    - dotnet/orleans
    - HangfireIO/Hangfire
    - nopSolutions/nopCommerce
    - ThreeMammals/Ocelot
    - OrchardCMS/OrchardCore
    - dotnetcore/CAP
    - gothinkster/aspnetcore-realworld-example-app

  Developer_Tools:
    - karpathy/nn-zero-to-hero

  # Future categories to expand research:
  # B2B_Solutions:
  #   - example/repo
  # 
  # Frontend_Frameworks:
  #   - example/repo
  # 
  # Backend_Infrastructure:
  #   - example/repo