# IT Jobs Watch configuration for London job market analysis

location:
  name: "London"
  id: "2649"  # ITJobsWatch location ID for London

technologies:
  - "C#"
  - "Python"
  - "TypeScript" 
  - "Software Engineering"
  - "Artificial Intelligence"

# Additional search terms that might be useful
alternative_searches:
  csharp_variants:
    - "C# Developer"
    - "C# Engineer"
    - ".NET Developer"
    - ".NET Core"
  
  python_variants:
    - "Python Developer"
    - "Python Engineer"
    - "Django Developer"
    - "Flask Developer"
  
  typescript_variants:
    - "TypeScript Developer"
    - "Angular Developer"
    - "React Developer"
    - "Node.js Developer"
  
  ai_variants:
    - "Machine Learning"
    - "Data Scientist"
    - "AI Engineer"
    - "Deep Learning"

# Scraping configuration
scraping:
  delay_seconds: 1.5
  max_retries: 3
  timeout_seconds: 30

# Output configuration  
output:
  csv_filename: "itjobswatch_stats.csv"
  metadata_filename: "itjobswatch_metadata.json"
  data_directory: "data/raw"