name: Collect GitHub Stats

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas jupyter python-dotenv
    
    - name: Run data collection
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        jupyter nbconvert --to python github_data_collector.ipynb
        python github_data_collector.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add github_repository_stats.csv github_stats_metadata.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update repository statistics [skip ci]" && git push)